### PR TITLE
controllers & k6 new relic tests

### PR DESCRIPTION
**Pull request by anthonysim**
1) controllers for GET POST PUT & DELETE using postgres,
2) k6 new relic test scripts for GETS & POSTS for 1, 10, 100  1000 RPS,
3) deleted unused files,
4) moved around files and folders to "clean" house.

### CODE REVIEW

**Comment by anthonysim** [comment]
image

**Comment by anthonysim** [comment]
Screen Shot 2021-05-18 at 1 14 17 PM

**Review by vbaobao — APPROVED** [review]
Is the __DELETE__  folder meant to be deleted entirely? Looks like you did a lot of clean-up. LGTM.

**Comment by anthonysim** [comment]
@vbaobao, thanks! Yup it's meant to be deleted eventually. I wanted to "keep" it, for now so I can refer to it real quick. They will all be deleted eventually.

**Pull request merged**
